### ISSUE TITLE
Option to set a custom symbol for the color/format highlight

### ISSUE THREAD

**Issue by ThatOverPowered** [nobu-sh/vscode-mc-color#1]
Title is self explenatory.

An option to change the symbol from "§" to "&" will come in handy.

Lets say the 99% of minecraft plugins (Bukkit) will read the "&" instead of "§" and changing the "&" to "§" manually (so the extension can highlight it) on the plugin config file will sometimes cause some problems.

Changed configuration:
![Captura](https://user-images.githubusercontent.com/50776804/161661392-83737535-6250-4705-90b2-5d19786df4d0.PNG)

Default configuration:
![Captura2](https://user-images.githubusercontent.com/50776804/161661625-04ad18ef-4881-41be-96f9-351c5b0a3607.PNG)

**Comment by nobu-sh** [comment]
Interesting, will most likely add a prefixes array to the config file then.
Thanks for the suggestion!

**Comment by ThatOverPowered** [comment]
Thanks, I'll be checking for new updates so.

**Comment by nobu-sh** [comment]
Added in 762a6d0cfe48232476d4c3f295fb0a3f50953d80 should be updated on VSCode Marketplace!
