### ISSUE TITLE
Adding "&" character support

### ISSUE THREAD

**Issue by RitzAtemo** [nobu-sh/vscode-mc-color#2]
Server plugins mostly use the "&" character. Is it possible to implement an additional use of symbols to define the color?

**Comment by nobu-sh** [comment]
Indeed. I have been busy with work. See #1.

**Comment by nobu-sh** [comment]
I will work on this once i get a chance.

**Comment by nobu-sh** [comment]
Added in 762a6d0cfe48232476d4c3f295fb0a3f50953d80 should be updated on VSCode Marketplace!
