### ISSUE TITLE
New Line Delimiter not working properly

### ISSUE THREAD

**Issue by Felix14-v2** [nobu-sh/vscode-mc-color#4]
With:
![image](https://user-images.githubusercontent.com/75726196/232237695-482c11ba-f5b8-4ad1-9720-c2d567e29dc0.png)

Without:
![image](https://user-images.githubusercontent.com/75726196/232237700-ca34cbbe-6be8-4b5f-8a64-915c2ebbee47.png)

[test file.zip](https://github.com/nobu-sh/vscode-mc-color/files/11239988/test.file.zip)

**Comment by nobu-sh** [comment]
ill look into it
