### ISSUE TITLE
Color format Token over Quotation mark

### ISSUE THREAD

**Issue by FlameFire26** [nobu-sh/vscode-mc-color#7]
For example :
- {"text":"Join §2Green team!","clickEvent":{"action":"run_command","value":"/scoreboard players set taskshow config 1"}}

This command will be colered all text after "§2", not only the expacted "Green team!".
Affected by this, the command in _clickEvent_ is all colered by green, losing its syntax highlight.

**Comment by nobu-sh** [comment]
You can end your string with `§r` or you can set `"` as a delimiter in `mc-color.delimiters`
