### ISSUE TITLE
Text formatting is not reset

### ISSUE THREAD

**Issue by iwdath** [nobu-sh/vscode-mc-color#8]
As seen in the screenshot, when using the `&` symbol, only the color is reset, but the formatting is not.
![image_2024-08-22_15-03-34](https://github.com/user-attachments/assets/bfa72ac4-16fc-4f2a-bcbc-111d31294b90)

While in Minecraft, formatting is reset automatically.
![2024-08-22_15 16 01](https://github.com/user-attachments/assets/b8f63304-922c-4f7b-bfe2-96cf44a32f5a)

I tried using `"mc-color.delimiters": ["&"]`, but because of this, the colors are not displayed.
![image_2024-08-22_15-22-08](https://github.com/user-attachments/assets/4e1cf70c-011d-4635-90bd-fc364828fa87)

I can use `&r`, but I would like the extension to work by default like Minecraft without extra symbols.

**Comment by nobu-sh** [comment]
Hmm interesting is this bedrock or java edition?

**Comment by iwdath** [comment]
This is java edition

**Comment by nobu-sh** [comment]
Alright, I'll update it today adding an option in the extension settings to replicate that Java behavior.

On bedrock edition all formatting carries over until the reset symbol is used.

Figures there is a discrepancy between the two.

**Comment by nobu-sh** [comment]
Added in https://github.com/nobu-sh/vscode-mc-color/pull/10
